#!/bin/bash
rm refs
x=1
while [ $x -le $1 ]
do
  curl -s -X POST http://localhost:8556/v1/order -H "accept: */*" -H "Content-Type: application/json" -d "{\"beneficiaryIDDocumentCID\":\"\"}" | jq .orderReference >> refs4 
  x=$(( $x + 1 ))
done





