#!/bin/bash
beneficiaryID="GisugaBj3LrtJ5eF1aRB13uxBt6SfGk4wErzLFaKKfZL"

while IFS= read -r line; do
    (curl -s -X POST http://localhost:5556/v1/order/secret -H "accept: */*" -H "Content-Type: application/json" -d "{\"orderReference\":$line,\"beneficiaryIDDocumentCID\":\"$beneficiaryID\"}") &
done < "refs"




