#!/bin/bash
beneficiaryID="5m4iJRCRzcMySHFXgAPB1gyfBvHgomwEpWDpZRHayPyP"

while IFS= read -r line; do
curl -s -X POST http://localhost:8556/v1/order/secret -H "accept: */*" -H "Content-Type: application/json" -d "{\"orderReference\":$line,\"beneficiaryIDDocumentCID\":\"$beneficiaryID\"}"
done < "refs4"




